config/routes.rb
Rails.application.routes.draw do
  root to: "letters#index"
  namespace :admin do
    resources :letters
  end
  resources :letters, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/letter.rb
class Letter < ApplicationRecord
  validates :reciever, :message, presence: true
  enum status: { pending: "pending", approved: "approved", archived: "archived" }

  after_create :update_json

  private

  def update_json
    home_dir = Dir.home
    file_path = Rails.root.join(home_dir, "Documentos", "correio_ap", "correio.json")

    FileUtils.mkdir_p(File.dirname(file_path))

    data = { id: self.id, mensagem: " * ** Eiii, #{self.reciever}!!!, Tenho um recadinho procê! Corre la pra vê   :love_letter: ** *" }

    File.write(file_path, JSON.pretty_generate(data))
  end
end

app/controllers/admin/letters_controller.rb
class Admin::LettersController < ApplicationController
  before_action :get_items

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    @letter = Letter.new(letter_params)

    @letter.save
    redirect_to admin_letters_path
  end

  def update
    @letter.update(letter_params)

    redirect_to admin_letters_path
  end

  def destroy
    @letter.update(status: "archived")

    redirect_to admin_letters_path
  end

  private

  def get_items
    @letters = Letter.order(status: :desc)
    @letter = Letter.find(params[:id]) rescue Letter.new
  end

  def letter_params
    params.require(:letter).permit(:sender, :reciever, :message, :status, :public)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  # before_action :set_letter, only: %i[ show edit update destroy ]
  before_action :get_items

  def index; end

  def new; end

  def show; end

  def create
    @letter = Letter.new(letter_params)
    @letter.save
    flash[:notice] = "Parabéns! Sua mensagem foi enviada. Assim que for aprovada, todos poderão vê-la :D"
    redirect_to new_letter_path
  end

  private

  def get_items
    letters = Letter.where(public: true, status: "approved").order(created_at: :desc)
    @letters = letters.limit(3)
    @letter = letters.first
  end

  def letter_params
    params.require(:letter).permit(:sender, :reciever, :message, :public).merge(status: "approved")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/admin/letters/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <%= method %>
      <%= form_with(model: [:admin, @letter], local: true, html: { class: "needs-validation" }) do |form| %>
        <% if letter.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(letter.errors.count, "error") %> prohibited this letter from being saved:</h4>
            <ul>
              <% letter.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="mb-3">
          <%= form.label :sender, class: "form-label" %>
          <%= form.text_field :sender, class: "form-control form-control-sm", required: true %>
        </div>
        <div class="mb-3">
          <%= form.label :reciever, class: "form-label" %>
          <%= form.text_field :reciever, class: "form-control form-control-sm", required: true %>
        </div>
        <div class="mb-3">
          <%= form.label :message, class: "form-label" %>
          <%= form.text_area :message, class: "form-control form-control-sm", rows: 5, required: true %>
        </div>
        <div class="row mb-3">
          <div class="col">
            <%= form.label :status, class: "form-label" %>
            <%= form.select :status, Letter.statuses.keys.map {|status| [status.humanize, status]}, {}, class: "form-select form-select-sm" %>
          </div>
          <div class="col">
            <%= form.label :public, class: "form-label" %>
            <%= form.select :public, [['No', false], ['Yes', true]], {}, class: "form-select form-select-sm" %>
          </div>
        </div>
        <div class="row mb-3">
          <div class="col">
            <%= form.submit "Submit", class: "btn btn-primary btn-sm w-100" %>
          </div>
          <div class="col">
            <%= link_to "Back to Letters", admin_letters_path, method: :get, class: "btn btn-secondary btn-sm w-100" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/letters/edit.html.erb
<div class="container">
  <%= render "admin/letters/form", letter: @letter, method: "put" %>
</div>

app/views/admin/letters/index.html.erb
<div class="container">
  <div class="row mx-2">
    <div class="col-md-3">
      <div class="mt-4">
        <%= link_to "New letter", new_admin_letter_path, method: :get, class: "btn btn-primary mt-3" %>
      </div>
    </div>
  </div>
  <div class="row mx-2">
    <div class="col-md-12">
      <div class="mt-4">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Sender</th>
              <th scope="col">Reciever</th>
              <th scope="col">Message</th>
              <th scope="col">Status</th>
              <th scope="col">Public</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @letters.each do |letter| %>
              <tr>
                <td><%= letter.sender %></td>
                <td><%= letter.reciever %></td>
                <td><%= letter.message.truncate(50) %></td>
                <td><%= letter.status.humanize %></td>
                <td><%= letter.public ? 'Yes' : 'No' %></td>
                <td>
                  <div class="btn-group" role="group" aria-label="Basic example">
                    <%= link_to "Editar", edit_admin_letter_path(letter), class: "btn btn-secondary btn-sm me-1" %>
                    <%= button_to "Arquivar", admin_letter_path(letter), method: :delete, data: { turbo_confirm: 'Você tem certeza?' }, class: "btn btn-danger btn-sm" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/letters/new.html.erb
<div class="container">
  <%= render "admin/letters/form", letter: @letter, method: "post" %>
</div>

app/views/admin/letters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @letter %>

<div>
  <%= link_to "Edit this letter", edit_letter_path(@letter) %> |
  <%= link_to "Back to letters", letters_path %>

  <%= button_to "Destroy this letter", @letter, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Correio Elegante</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playwrite+AU+SA:wght@100..400&family=Playwrite+BR:wght@100..400&display=swap" rel="stylesheet">
  </head>
  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/letters/_form.html.erb
 <div class="form-paper">

  <div class="flash-messages">
    <% flash.each do |key, value| %>
      <div class="alert alert-success d-block flash <%= key %>"><%= value %></div>
    <% end %>
  </div>

  <%= form_with(model: Letter.new, url: letters_path, method: :post, local: true, html: { class: "needs-validation" }) do |form| %>
    
    <div class="row">
      <div class="col-6">
        <div class="mb-3">
          <%= form.text_field :sender, class: "form-control form-control-sm", placeholder: "De:", required: true %>
        </div>
      </div>
      <div class="col-6">
        <div class="mb-3">
          <%= form.text_field :reciever, class: "form-control form-control-sm", placeholder: "Para: ", required: true %>
        </div>
      </div>
    </div>
    <div class="mb-3">
      <%= form.text_area :message, class: "form-control form-control-sm", rows: 5, placeholder: "Mande aqui a sua melhor mensagem :)", required: true %>
    </div>
    <div class="row mb-3">
      <div class="col">
        <%= form.submit "Enviar", class: "btn btn-wood" %>
      </div>
    </div>
  <% end %>
</div>

app/views/letters/index.html.erb
<style>
  *{
    margin: 0;
    padding: 0;
  }
  html, body{
    width:  100%;
    height:  100%;
  }

  body{
    background: #4F3F92;
    font-family: "Playwrite AU SA", cursive;
    overflow:hidden;
  }

  @keyframes float {
    0% {
      transform: translate(0, 0);
    }
    50% {
      transform: translate(8px, -20px);
    }
    100% {
      transform: translate(0, 0)
    }
  }

  .logo{
    left: 26px;
    top: 26%;
    width: 350px;
  }

  .container-fluid{
    height:100vh;
  }
  .container-fluid:before{
    content: '';
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    height: 160px;
    width: 100%;
    background: #3D2A8D;
    z-index: -3;
  }

  .l-flag{ left: 0; animation: float_left 3s ease-in-out infinite; }
  .r-flag{ right: 0; animation: float_right 3s ease-in-out infinite; }
  .c-lamps{ left: calc(50% - 292px); animation: float 4s ease-in-out infinite; }

  .l-foods{ left: -80px; bottom: -25px; width: 480px; }
  .c-bonfire{ bottom: -50px; left: calc(50% - 116px);  }
  .r-foods{ right: -80px; bottom: -25px; width: 480px; }



  .fireworks{ position: absolute; }
  .fwb{
    top: 25%;
    right: 36px;
    animation: fireworks 1.5s ease-in-out infinite;
  }

  .fw{
    top: 62%;
    right: 190px;
    animation: fireworks 1.0s ease-in-out infinite;
  }

  .f2w{
    top: 53%;
    left: 180px;
    animation: fireworks 1.2s ease-in-out infinite;
  }


  @keyframes float_left {
    0% {
      transform: translate(0, 0);
    }

    50% {
      transform: translate(-15px, -10px);
    }

    100% {
      transform: translate(0, 0)
    }
  }

  @keyframes float_right {
    0% {
      transform: translate(0, 0);
    }

    50% {
      transform: translate(15px, -10px);
    }

    100% {
      transform: translate(0, 0)
    }
  }

  @keyframes fireworks {
    0% {
      transform: scale(0);
      opacity: 1;
    }
    50% {
      transform: scale(1);
      opacity: 1;
    }
    100% {
      transform: scale(1);
      opacity: 0;
    }
  }


  .first-letter{
    padding: 26px 120px;
    max-width: 1110px;
    background: url("/src/letter.png") no-repeat center center;
    background-size:cover;
    min-height: 530px;
  }

  .small-letter{
    padding: 26px 44px;
    max-width: 1110px;
    background: url("/src/letter.png") no-repeat center center;
    background-size:cover;
    min-height: 280px;
    opacity: 0.85;
  }
</style>
<div class="container-fluid px-0 position-relative overflow-hidden pb-5">
  <img src="/src/flags_left.svg" class="position-fixed top-0 l-flag" />
  <img src="/src/lamps.svg" class="position-fixed c-lamps" />
  <img src="/src/flags_right.svg" class="position-fixed top-0 r-flag" />
  <img src="/src/logo.svg" class="position-fixed logo" />
  <img src="/src/foods_left.svg" class="position-fixed l-foods" />
  <img src="/src/bonfire.svg" class="position-fixed c-bonfire" />
  <img src="/src/foods_right.svg" class="position-fixed r-foods" />
  <img src="/src/fireworks.svg" class="fireworks fwb" />
  <img src="/src/food_fireworks.svg" class="fireworks fw" />
  <img src="/src/food_2_fireworks.svg" class="fireworks f2w" />
  <div class="container pb-5" style="padding-top: 136px; position: relative; z-index: 5;">
    <div class="row">
      <div class="col-12">
        <div class="d-flex flex-column align-items-center justify-content-center text-center first-letter m-auto">
          <article class="d-flex flex-column">
            <h6 class="fw-bold fs-5 text-secondary">
              <span class="text-dark">De:</span> <%= @letter.sender %>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <span class="text-dark">Para:</span> <%= @letter.reciever %>
            </h6>
            <span class="mt-3 fs-4 text-dark"><%= @letter.message %></span>
          </article>
        </div>
      </div>
    </div>
    <div class="row px-5 mt-3">
      <% @letters.each_with_index do |item, index| %>
        <% next if item.id.eql?(@letter.id) %>
        <div class="col-6">
          <div class="d-flex flex-column align-items-center justify-content-center text-center small-letter m-auto">
            <article class="d-flex flex-column">
              <h6 class="fw-bold fs-6 text-secondary">
                <span class="text-dark">De:</span> <%= item.sender %>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="text-dark">Para:</span> <%= item.reciever %>
              </h6>
              <span class="mt-3 fs-6 text-dark"><%= item.message %></span>
            </article>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  setTimeout(() => {
    location.reload();
  }, 180000);
</script>

app/views/letters/new.html.erb
<style>
*{
  margin: 0;
  padding: 0;
}
html, body{
  width:  100%;
  height:  100%;
}

body{
  background: #4F3F92;
  font-family: "Playwrite AU SA", cursive;
  overflow:hidden;
}

@keyframes float {
  0% {
    transform: translate(0, 0);
  }
  50% {
    transform: translate(8px, -20px);
  }
  100% {
    transform: translate(0, 0)
  }
}

.logo{
  left: 26px;
  top: 26%;
  width: 350px;
}

.container-fluid{
  height:100vh;
}
.container-fluid:before{
  content: '';
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  height: 160px;
  width: 100%;
  background: #3D2A8D;
  z-index: -3;
}

.l-flag{ left: 0; animation: float_left 3s ease-in-out infinite; }
.r-flag{ right: 0; animation: float_right 3s ease-in-out infinite; }
.c-lamps{ left: calc(50% - 292px); animation: float 4s ease-in-out infinite; }

.l-foods{ left: -80px; bottom: -25px; width: 480px; }
.c-bonfire{ bottom: -50px; left: calc(50% - 116px);  }
.r-foods{ right: -80px; bottom: -25px; width: 480px; }



.fireworks{ position: absolute; }
.fwb{
  top: 25%;
  right: 36px;
  animation: fireworks 1.5s ease-in-out infinite;
}

.fw{
  top: 62%;
  right: 190px;
  animation: fireworks 1.0s ease-in-out infinite;
}

.f2w{
  top: 53%;
  left: 180px;
  animation: fireworks 1.2s ease-in-out infinite;
}


@keyframes float_left {
  0% {
    transform: translate(0, 0);
  }

  50% {
    transform: translate(-15px, -10px);
  }

  100% {
    transform: translate(0, 0)
  }
}

@keyframes float_right {
  0% {
    transform: translate(0, 0);
  }

  50% {
    transform: translate(15px, -10px);
  }

  100% {
    transform: translate(0, 0)
  }
}

@keyframes fireworks {
  0% {
    transform: scale(0);
    opacity: 1;
  }
  50% {
    transform: scale(1);
    opacity: 1;
  }
  100% {
    transform: scale(1);
    opacity: 0;
  }
}

.form-paper{
  margin: 0 auto;
  padding: 80px 120px 0 120px;
  max-width: 1110px;
  background: url("/src/letter.png") no-repeat center center;
  background-size:cover;
  min-height: 530px;
}
  .form-control{
    border: 0px;
    border-radius: 0;
    font-size: 16px;
    padding: 16px 12px;
    color: #2C2353;
    border-bottom: 2px solid #aaa;
    background: none; 
  }
  .form-control:focus {
    border-color: inherit; /* Mantém a cor da borda original */
    box-shadow: none; /* Remove a sombra */
    outline: none; /* Remove o contorno */
    background-color: inherit; /* Mantém a cor de fundo original */
}

.btn-wood{
  display: block; 
  margin: 0 auto;
  background: url("/src/wood_button.svg") no-repeat center center;
  background-size: cover;
  width:155px;
  height:64px; 
  color: #222;
  font-weight: bold;
}

</style>

<div class="container-fluid px-0 position-relative overflow-hidden pb-5">
  <img src="/src/flags_left.svg" class="position-fixed top-0 l-flag" />
  <img src="/src/lamps.svg" class="position-fixed c-lamps" />
  <img src="/src/flags_right.svg" class="position-fixed top-0 r-flag" />

  <img src="/src/logo.svg" class="position-fixed logo" />

  <img src="/src/foods_left.svg" class="position-fixed l-foods" />
  <img src="/src/bonfire.svg" class="position-fixed c-bonfire" />
  <img src="/src/foods_right.svg" class="position-fixed r-foods" />

  <img src="/src/fireworks.svg" class="fireworks fwb" />
  <img src="/src/food_fireworks.svg" class="fireworks fw" />
  <img src="/src/food_2_fireworks.svg" class="fireworks f2w" />

  <div class="container pb-5" style="padding-top: 190px; position: relative; z-index: 5;">
    <div class="row">
      <div class="col-12">
        <%= render "form", letter: @letter, method: :post %>
      </div>
    </div>
  </div>
</div>

app/views/letters/show.html.erb
<div class="container">
  <div class="row mx-2">
    <div class="col-md-12">
      <div class="mt-4">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">De</th>
              <th scope="col">Para</th>
              <th scope="col">Mensagem</th>
            </tr>
          </thead>
          <tbody>
            <% Letter.all.order(created_at: :desc).each do |letter| %>
              <tr>
                <td><%= letter.sender %></td>
                <td><%= letter.reciever %></td>
                <td><%= letter.message %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>